countryDBDetails:
  - countryCode: "TW"
    url: "jdbc:mysql://localhost:3306/SPRING_DEMO"
    username: "encryptedUsername"
    password: "encryptedPassword"

---
dbDetails:
  driverClassName: "com.mysql.cj.jdbc.Driver"

---
jasypt:
  encryptor:
    password: "ourPassword"