countryDBDetails:
  - countryCode: "TW"
    url: "jdbc:mysql://localhost:3306/SPRING_DEMO"
    username: "ENC(encryptedUsername)"
    password: "ENC(encryptedPassword)"

---
dbDetails:
  driverClassName: "com.mysql.cj.jdbc.Driver"
